# docker build -t="dogtail9/vsts-agent-windows-base" -f="Dockerfile.Windows.Base" .
# docker run --rm -d -e VSTS_ACCOUNT=<ACCOUNT> -e VSTS_TOKEN=<TOKEN> -it dogtail9/vsts-agent-windows-base

FROM microsoft/windowsservercore
ENV AGENT_VERSION=2.107.1

WORKDIR ./Agent

RUN powershell -Command $ErrorActionPreference = 'Stop' ; \ 
                        (New-Object System.Net.WebClient).DownloadFile('https://github.com/Microsoft/vsts-agent/releases/download/v2.107.1/vsts-agent-win7-x64-2.107.1.zip', 'agent.zip') ; \  
                        Expand-Archive agent.zip -DestinationPath $PWD ; \
                        Remove-Item -Force agent.zip ;                        

COPY ./start.ps1 .

ENTRYPOINT ["powershell", "-Command"]
CMD ["./start.ps1"]
