# docker build -t="dogtail9/vsts-agent-windows-base" -f="Dockerfile.Windows.Base" .
# docker run --rm -d -e VSTS_ACCOUNT=<ACCOUNT> -e VSTS_TOKEN=<TOKEN> -it dogtail9/vsts-agent-windows-base

# docker build -t="dogtail9/vsts-agent-windows-grunt" -f="Dockerfile.Windows.Grunt" .

FROM dogtail9/vsts-agent-windows-node

RUN powershell -Command \
    npm install -g grunt ; \
    npm install -g gulp ; 